onlyBuiltDependencies:
  - esbuild
  - workerd

overrides:
  rollup: '>=4.59.0'
  fast-xml-parser: '>=5.3.6'
  ajv: '>=8.18.0'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
  wrangler@>=4.0.0 <4.59.1: '>=4.59.1'
